#! /bin/bash

VENDOR=tmz
ENV=test
REGION=us-west-2

display_help () {
  echo "
Available options:
  --vendor    Vendor name [default=tmz]
  --env       Environment name [default=test]
  --region    Region name [default=us-west-2]
  --help      This message
"
}

for opt in "$@"
do
case ${opt} in
  --vendor=*)
    VENDOR=${opt#*=}
  ;;
  --env=*)
    ENV=${opt#*=}
  ;;
  --region=*)
    REGION=${opt#*=}
  ;;
  --help)
    display_help
    exit
  ;;
  *)
  display_help
  exit
;;
esac
done

rm "$HOME/.aws/$VENDOR-docker"
cp "$HOME/.aws/BY_ENV/$VENDOR-docker-$ENV-$REGION" "/Users/xejacobs/.aws/$VENDOR-docker"
echo "copied $ENV $REGION creds for $VENDOR"
echo ""
echo "$HOME/.aws/$VENDOR-docker:"
echo ""
echo "$(cat "$HOME/.aws/$VENDOR-docker")"