#! /bin/bash

VENDOR=tmz
ENV=test

display_help () {
  echo "
Available options:
  --vendor    Vendor name [default=tmz]
  --env       Environment name [default=test]
  --help      This message
"
}

for opt in "$@"
do
case ${opt} in
  --vendor=*)
    VENDOR=${opt#*=}
  ;;
  --env=*)
    ENV=${opt#*=}
  ;;
  --help)
    display_help
    exit
  ;;
  *)
  display_help
  exit
;;
esac
done

rm "$HOME/.aws/$VENDOR-docker"
cp "$HOME/.aws/BY_ENV/$VENDOR-docker-$ENV" "/Users/xejacobs/.aws/$VENDOR-docker"
echo "copied $ENV creds for $VENDOR"