#! /bin/bash

PROFILE=tmz-docker
REGION=us-west-2
ACCOUNTID=345746658229
BUILD=''


display_help () {
  echo "
Available options:
  --build     If you want to build the container as it is brought up
  --region    Region name [default=us-west-2]
  --help      This message
"
}


if [[ "$PWD" == *"toofab"* ]]; then
  PROFILE=toofab-docker
fi

if [[ "$PWD" == *"eme"* ]]; then
  PROFILE=eme-docker
  ACCOUNTID=191377549562
fi


for opt in "$@"
do
case ${opt} in
  --region=*)
    REGION=${opt#*=}
  ;;
  --build)
    BUILD='--build'
  ;;
  --help)
    display_help
    exit
  ;;
  *)
  display_help
  exit
;;
esac
done

# if ! docker info > /dev/null 2>&1; then
#   open -a Docker
# fi

rm -rf var
git checkout var/.gitkeep
sleep 5

#docker login
COMMAND="aws ecr get-login-password --region $REGION --profile $PROFILE | docker login --password-stdin --username AWS $ACCOUNTID.dkr.ecr.$REGION.amazonaws.com"
echo "Running: $COMMAND"
echo $COMMAND | bash

# docker kill $(docker ps -q)
COMMAND="docker-compose up $BUILD ; docker-compose down"
echo "Running: $COMMAND"
echo $COMMAND | bash