#! /bin/bash

case $1 in
  admin-ui-plugin-js)
    cd /Users/xejacobs/Documents/TMZ\ Dev/triniti/admin-ui-plugin-js;
    ;;
  cms-js)
    cd /Users/xejacobs/Documents/TMZ\ Dev/triniti/cms-js;
    ;;
  curator-php)
    cd /Users/xejacobs/Documents/TMZ\ Dev/triniti/curator-php;
    ;;
  efjacobson)
    cd /Users/xejacobs/Documents/TMZ\ Dev/efjacobson;
    ;;
  ovp-php)
    cd /Users/xejacobs/Documents/TMZ\ Dev/triniti/ovp-php;
    ;;
  pbj-php)
    cd /Users/xejacobs/Documents/TMZ\ Dev/gdbots/pbj-php;
    ;;
  playground)
    cd /Users/xejacobs/Documents/TMZ\ Dev/efjacobson/playground;
    ;;
  tmz-amp)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-amp;
    ;;
  tmz-ncr)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-ncr;
    ;;
  tmz-ovp)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-ovp;
    ;;
  tmz-pbjx)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-pbjx;
    ;;
  tmz-share)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-share;
    ;;
  toofab-api)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/toofab-api;
    ;;
  toofab-core-php)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/toofab-core-php;
    ;;
  toofab-cms)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/toofab-cms;
    ;;
  toofab-schemas)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/toofab-schemas;
    ;;
  tmz-api)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-api;
    ;;
  tmz-cms)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-cms;
    ;;
  tmz-core-php)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-core-php;
    ;;
  tmz-feeds)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-feeds;
    ;;
  tmz-schemas)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-schemas;
    ;;
  tmz-web)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/tmz-web;
    ;;
  triniti/schemas)
    cd /Users/xejacobs/Documents/TMZ\ Dev/triniti/schemas;
    ;;
  wb-devops)
    cd /Users/xejacobs/Documents/TMZ\ Dev/wb-apps/wb-devops;
    ;;
  *)
    echo "dunno what that is bro";
    ;;
esac