#! /bin/bash

branch_name="$1"
if [ "$branch_name" == "" ]; then
  echo "you must enter a branch name"
else
  if [ "$branch_name" == "develop" ]; then
    echo "don't delete develop, fool"
  else
    if [ "$branch_name" == "master" ]; then
      echo "don't delete master, fool"
    else
      if [ "$(git branch --list $branch_name)" ]; then
        git branch -D "$branch_name"
        else
        echo "$branch_name does not exist"
      fi
    fi
  fi
fi
