#! /bin/bash

branch=$(git symbolic-ref --short HEAD)
is_master=$(git ls-remote --heads origin master)

if [[ -z "$is_master" ]]; then
  git checkout -q main && git fetch -q && git pull -q origin main && git checkout -q "$branch"
else
  git checkout -q master && git fetch -q && git pull -q origin master && git checkout -q "$branch"
fi
