#! /bin/bash

BRANCH=$(git symbolic-ref --short HEAD)
IS_MASTER=$(git ls-remote --heads origin master)

if [[ -z "$IS_MASTER" ]]; then
  git checkout main && git fetch && git pull origin main && git checkout $BRANCH
else
  git checkout master && git fetch && git pull origin master && git checkout $BRANCH
fi
