#! /bin/bash

append=''

display_help() {
  echo "
Available options:
  --pull-requests
   -pr                If you want to open the list of pull requests
  --branches
   -b                 If you want to open the list of branches
  --releases
   -r                 If you want to open the list of releases
  --help
   -h                 This message
"
}

for opt in "$@"; do
  case ${opt} in
  -pr | --pull-requests)
    append='pulls/'
    ;;
  -b | --branch)
    append='branches/'
    ;;
  -r | --releases)
    append='releases/'
    ;;
  --help)
    display_help
    exit
    ;;
  *)
    display_help
    exit
    ;;
  esac
done

function repo() {
  vendor="$1"
  custom_repo="$2"
  if [ -n "$custom_repo" ]; then
    open -a "Brave Browser" -n --args --new-tab "https://github.com/tmz-apps/$vendor-$custom_repo/$append"
    return 0
  fi

  apps=(amp api cms feeds ncr pbjx share web)

  for app in "${apps[@]}"; do
    open -a "Brave Browser" -n --args --new-tab "https://github.com/tmz-apps/$vendor-$app/$append"
  done
  return 0
}

repo tmz
repo tmz ovp
repo tmz app
repo toofab
